# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_equivariant <- function(X, mfdname) {
    .Call('_RiemRegress_cpp_equivariant', PACKAGE = 'RiemRegress', X, mfdname)
}

elocal_fit_cv <- function(h, ytrain, ytest, xtrain, xtest, mfdname) {
    .Call('_RiemRegress_elocal_fit_cv', PACKAGE = 'RiemRegress', h, ytrain, ytest, xtrain, xtest, mfdname)
}

elocal_fit <- function(h, y, x, mfdname) {
    .Call('_RiemRegress_elocal_fit', PACKAGE = 'RiemRegress', h, y, x, mfdname)
}

elocal_predict <- function(h, y, x, xpredict, mfdname) {
    .Call('_RiemRegress_elocal_predict', PACKAGE = 'RiemRegress', h, y, x, xpredict, mfdname)
}

rcpparma_hello_world <- function() {
    .Call('_RiemRegress_rcpparma_hello_world', PACKAGE = 'RiemRegress')
}

rcpparma_outerproduct <- function(x) {
    .Call('_RiemRegress_rcpparma_outerproduct', PACKAGE = 'RiemRegress', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_RiemRegress_rcpparma_innerproduct', PACKAGE = 'RiemRegress', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_RiemRegress_rcpparma_bothproducts', PACKAGE = 'RiemRegress', x)
}

